name: 'Setup HashiCorp tool'
description: 'Install a binary release of a HashiCorp tool from releases.hashicorp.com'
author: 'Nick Ethier'
inputs:
  product:
    required: true
    description: 'The product this action should install.'
  version:
    required: true
    description: 'The version of the product which should be installed. Supports semver spec and ranges'
runs:
  using: 'node12'
  main: 'dist/index.js'
